### ISSUE TITLE
goapp test fails

### ISSUE THREAD

**Issue by raphael** [google/weasel#2]
I'm getting the following when running `goapp test`:

```
❯ ~/go_appengine/goapp test
# github.com/goadesign/goa.design/appengine/server
package github.com/goadesign/goa.design/appengine/server (test)
        imports github.com/google/weasel/internal: use of internal package not allowed
FAIL    github.com/goadesign/goa.design/appengine/server [setup failed]
```

This used to work but it looks like the code is now using an internal package which `goapp` doesn't like...

**Comment by x1ddos** [comment]
Correct. `internal` is not allowed to be imported.
What is/are the type(s) that you're trying to import?

Btw, I'm refactoring server package these days. Will make it exported so that a custom server can be built on top of it.

**Comment by raphael** [comment]
This was my mistake, I had forgotten to change the import path from this package "internal" to my fork.
