### ISSUE TITLE
Absolute redirects

### ISSUE THREAD

**Issue by raphael** [google/weasel#3]
There are a number of files in my GCS bucket that have moved or just don't exist anymore however there are outstanding external links to them.

It is fairly simple to add a section to `config.json` that lists "absolute" redirects where the redirect does not append the original request path.

I'm thinking something like:
`config.json`:
```json
  "absolute-redirects": {
    "/getting-started.html": "https://goa.design/learn/guide",
    "/goagen.html": "https://goa.design/implement/goagen",
    "/vice-framework": "https://goa.design",
    "/swagger.html": "https://goa.design/design/swagger"
  },
```
The server code would then be tweaked to not append the original request path for these, something like:
`server.go`:
```go
func init() {
// ...
	for path, redir := range config.AbsoluteRedirects {
		http.Handle(path, redirectHandler(redir, http.StatusMovedPermanently, true))
	}
	for host, redir := range config.Redirects {
		http.Handle(host, redirectHandler(redir, http.StatusMovedPermanently, false))
	}
//...
}

// ...

func redirectHandler(url string, code int, abs bool) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		u := url
		if !abs {
			u += r.URL.Path
		}
// ....
```
 Would you consider a PR that does the above?

**Comment by x1ddos** [comment]
This is already implemented. See example config here: https://github.com/google/weasel/blob/a785d75dfea6c0f0233711e878a216038400de35/server/config.json.sample#L3

**Comment by raphael** [comment]
As far as I understand what `redirects` does is append the redirected path to the redirect target (what I would call a "relative" redirect). What I needed was an "absolute" redirect. Unless I'm missing something I don't think this issue should be closed.

**Comment by x1ddos** [comment]
if `host` is `example.com` and `another.host` is `another.example.com`, then

```
"host/": "https://another.host"
```
will redirect:

* `example.com` to `https://another.example.com`
* `example.com/foo/bar?foo=bar` to `https://another.example.com/foo/bar?foo=bar`

Isn't that what you need?

**Comment by raphael** [comment]
No I need to be able to redirect to a different path, not just a different host. If you look at my initial comment you'll see for example:

    "/getting-started.html": "https://goa.design/learn/guide"

which redirects:

    "goa.design/getting-started.html" to "https://goa.design/learn/guide"

**Comment by x1ddos** [comment]
Ah, I see. Sorry for misreading. That can be done with the std http package, no need for weasel:

```go
http.Handle("/getting-started.html", http.RedirectHandler("https://goa.design/learn/guide", 301))
```

**Comment by raphael** [comment]
Right that's how I ended up [implementing](https://github.com/goadesign/goa.design/blob/master/appengine/server/server.go#L36-L38) the "absolute redirect" feature, just thought it would be useful for these redirects to also appear in the config to keep all these things in one place.

**Comment by x1ddos** [comment]
Right. I'm trying to move weasel away from imposing a certain config format. Working on a change to leave the config part up to the user and provide some examples instead.

**Comment by raphael** [comment]
Sounds good, looking forward to it!

**Comment by x1ddos** [comment]
Cool. I'll mention you in a PR for a review. Thanks!
