### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by derekperkins** [google/weasel#6]
@crhym3 Just wanted to see what your plans are for this repo moving forward. @raphael's suggested changes all seem great.

**Comment by crhym3** [comment]
Hey @derekperkins I'm not sure how but I missed all notifications from @raphael's issues. Or maybe github never sent me those.

In any case, thanks so much for pinging me. I'll check out all @raphael's suggestion. The plan is to make this more robust and better :) so, all suggestions are welcome.

**Comment by derekperkins** [comment]
Awesome! This is a pretty cool extension.
